---
title: '5/3 R 프로그래밍 학습일지6'
author: "Nigella"
date: '2021/5/3'
output:
  html_document:
    keep_md: true
    fig_height: 6
    fig_width: 10
    highlight: textmate
    theme: cosmo
    toc: yes
    toc_depth: 3
    toc_float: yes
---


## 데이터프레임 생성
```{r}
fruit <- data.frame(제품 = c("사과","딸기","수박"),
                    가격 = c(1800, 1500,3000),
                    판매량 = c(24,38,13))

a=mean(fruit$가격); b=mean(fruit$판매량)
cat("과일 가격 평균:", a,"\t","과일 판매량 평균:",b)
```

## 외부데이터 이용하기

### 엑셀, csv, rds 파일 불러오기 및 저장하기
```{r}
#install.packages("readxl")
library(readxl)
df_exam <- read_excel("./Data/excel_exam.xlsx")
head(df_exam)
mean(df_exam$english)
mean(df_exam$science)

# 첫 번째 행을 변수명이 아닌 데이터로 인식
df_exam_novar <- read_excel("./Data/excel_exam_novar.xlsx", col_names=F)
head(df_exam_novar)
#?read_excel()

# 엑셀 파일에 시트가 여러 개 있는 경우
df_exam_sheet <- read_excel("./Data/excel_exam_sheet.xlsx", sheet=3)
head(df_exam_sheet)

# CSV 파일 불러오기
df_csv_exam <- read.csv("./Data/csv_exam.csv")
head(df_csv_exam)
str(df_csv_exam)
df_csv_exam$class <- as.factor(df_csv_exam$class)
summary(df_csv_exam)
table(df_csv_exam$class)

# 문자가 들어 있는 파일일 경우: Factor type
df_csv_exam <- read.csv("./Data/csv_exam.csv", stringsAsFactors=F)

# csv 파일로 저장하기
write.csv(fruit, file="./Data/fruit.csv")
#write.csv(df_midterm, file="./Data/df_midterm.csv")

# RDS 파일은 R 전용 데이터 파일로 다른 파일에 비해 R에서 읽고 쓰는 속도가 빠르고 용량이 작다는 장점이 있다.
# RDS 파일로 저장하기
saveRDS(fruit, file="./Data/fruit.rds")
# RDS 파일 불러오기
rm(fruit) # 데이터 삭제
fruit <- readRDS("./Data/fruit.rds")
fruit
```

## 실습

```{r}
library(ggplot2)
library(dplyr)

df_raw <- data.frame(var1=c(1,2,1),
                     var2 = c(2,3,2))
df_new <- df_raw
str(df_new)
df_new <- rename(df_new, v2 = var2)

df_mpg <- as.data.frame(mpg)
str(df_mpg)
df_mpg <- rename(df_mpg, city = cty, highway = hwy)
df_mpg$total <- (df_mpg$city + df_mpg$highway)/2
head(df_mpg)
mean(df_mpg$total)
summary(df_mpg$total)
hist(df_mpg$total)

# 조건문
df_mpg$test <- ifelse(df_mpg$total>=20, "pass", "fail")
# 빈도확인
table(df_mpg$test)
qplot(df_mpg$test)

# 중첩 조건문
df_mpg$grade <- ifelse(df_mpg$total>=30, "A", 
                       ifelse(df_mpg$total>=20, "B", "c"))
# 빈도확인
table(df_mpg$grade)
qplot(df_mpg$grade)
```

## 실습) 123page

```{r}
df_midwest <- as.data.frame(midwest)
str(df_midwest)
summary(df_midwest)

df_midwest <- rename(df_midwest, total = poptotal, asian = popasian)
df_midwest$ratio <- (df_midwest$asian/df_midwest$total)*100
hist(df_midwest$ratio)

df_midwest$size <- ifelse(df_midwest$ratio > mean(df_midwest$ratio), "large", "small")
table(df_midwest$size)
qplot(df_midwest$size)
```

## 데이터 가공하기

```{r}
str(df_exam)
df_exam <- as.data.frame(df_exam)
df_exam$class <- as.factor(df_exam$class)
# 조건에 맞는 데이터만 추출하기
df_exam %>% filter(class == 1)
df_exam %>% filter(class == 2)
df_exam %>% filter(class != 1)
df_exam %>% filter(math > 50)
df_exam %>% filter(english >= 80)
# 여러 조건 충족하는 행 추출하기
df_exam %>% filter(class == 1 & math >= 50)
# 여러 조건 중 하나 이상 충족하는 행 추출하기
df_exam %>% filter(math >= 90 | english >= 90)
# 목록에 해당하는 행 추출하기
df_exam %>% filter(class ==1|class==3|class==5)
df_exam %>% filter(class %in% c(1,3,5))
# 추출한 행으로 데이터 만들기
class1 <- df_exam %>% filter(class==1)
class2 <- df_exam %>% filter(class==2)
mean(class1$math)
mean(class2$math)
```

## 실습) 133page
```{r}
head(df_mpg)
#1
down_displ <- df_mpg %>% filter(displ<=4)
up_displ <- df_mpg %>% filter(displ>=5)
mean(down_displ$highway)
mean(up_displ$highway)
#2
manu_a <- df_mpg %>% filter(manufacturer=="audi")
manu_t <- df_mpg %>% filter(manufacturer=="toyota")
mean(manu_a$city)
mean(manu_t$city)
#3
msnu3 <- df_mpg %>% filter(manufacturer %in% c('chevrolet','ford','honda'))
mean(msnu3$highway)
```
